apiVersion: v1
kind: Service
metadata:
    name: redis-master
    labels:
        app: redis
        role: master
        tier: backend
spec:
    ports:
      - port: 6379
        targetPort: 6379
    # groups the pods we made earlier selecting via these tags
    selector:
        app: redis
        role: master
        tier: backend
